robertheim_topictags_controller:
    pattern: /tags
    defaults: { _controller: robertheim.topictags.controller:show }
robertheim_topictags_show_tag_controller:
    pattern: /tag/{tags}/{mode}
    defaults: { _controller: robertheim.topictags.controller:show_tag, mode: 'AND'}

